### PR TITLE
Add initial messaging host service for v8 workloads

### PR DESCRIPTION
**Pull request by kthomas**
This PR continues the host services architecture as created in https://github.com/synadia-io/nex/pull/118.

Host services are implemented using an RPC-based architecture in which the agent communicates with the node via the internal NATS connection. The v8 execution provider exposes a `hostServices` object on the global context and supports the messaging service as a result of this PR.

The following messaging methods are available to v8 functions in nex:

- `hostServices.messaging.publish('my.nats.subject', 'some payload....')`
- `hostServices.messaging.request('my.nats.req.subject', 123)`
- `hostServices.messaging.requestMany('my.nats.reqmany.subject', 'some req payload...')`

To test, deploy a v8 workload using the `messaging.js` v8 example:

```
(subject, payload) => {
  this.hostServices.messaging.publish('hello.world', payload);

  var req;
  var reqEx;

  var reqMany;
  var reqManyEx;

  try {
    req = this.hostServices.messaging.request('hello.world.request', payload);
  } catch (e) {
    reqEx = e;
  }

  try {
    reqMany = this.hostServices.messaging.requestMany('hello.world.request.many', payload);
  } catch (e) {
    reqManyEx = e;
  }

  return {
    'hello.world.request': req,
    'hello.world.request.ex': reqEx,
    'hello.world.request.many': reqMany,
    'hello.world.request.many.ex': reqManyEx
  }
};
```

`nex devrun ./examples/v8/echofunction/src/messaging.js --trigger_subject=hello`

Send a request to the `hello` subject:

`nats req hello 'payload'`

The nex node logs will show you the various messaging host services RPC requests received from the agent:

```
time=2024-02-25T21:44:45.170-05:00 level=DEBUG msg="Received host services RPC request" vmid=cndvl6o2btf7tv4bifh0 namespace=default workload=messagingjs service=messaging method=publish payload_size=7
time=2024-02-25T21:44:45.171-05:00 level=DEBUG msg="Received host services RPC request" vmid=cndvl6o2btf7tv4bifh0 namespace=default workload=messagingjs service=messaging method=request payload_size=7
time=2024-02-25T21:44:45.171-05:00 level=DEBUG msg="failed to send 7-byte request on subject hello.world.request: nats: no responders available for request"
time=2024-02-25T21:44:45.173-05:00 level=DEBUG msg="Received host services RPC request" vmid=cndvl6o2btf7tv4bifh0 namespace=default workload=messagingjs service=messaging method=requestMany payload_size=7
time=2024-02-25T21:44:48.180-05:00 level=DEBUG msg="Received response from execution via trigger subject" vmid=cndvl6o2btf7tv4bifh0 trigger_subject=hellotrigger workload_type=v8 function_run_time_nanosec=3011266797 payload_size=162
```

Since this basic example naively attempts to make requests against subjects that have no active subscriptions, exceptions are thrown and handled by the `messaging.js` example function where appropriate.

Running `task test` tests this functionality by setting up relevant subscriptions and responding to messages on the `hello.world.request` and `hello.world.request.many` subjects.

### CODE REVIEW

**Comment by autodidaddict** [comment]
Is there a way to specify a wait timeout on requestMany?

**Comment by kthomas** [comment]
> Is there a way to specify a wait timeout on requestMany?

Currently we are not allowing the user to specify a timeout. The timeout for a single `requestMany` request is 3 seconds and the timeout for a single message is 500 milliseconds. When individual messages are available sooner than 500ms, they are obviously delivered as soon as they become available.

It _would_ be nice to allow the user to specify these timeouts per request, obviously with the overall timeout being capped to some upper bound (like 3 seconds). I think we should consider that design since it could be more of a global pattern we want to implement for trigger functions more generally.

**Comment by autodidaddict** [comment]
> > Is there a way to specify a wait timeout on requestMany?
> 
> Currently we are not allowing the user to specify a timeout. The timeout for a single `requestMany` request is 3 seconds and the timeout for a single message is 500 milliseconds. When individual messages are available sooner than 500ms, they are obviously delivered as soon as they become available.
> 
> It _would_ be nice to allow the user to specify these timeouts per request, obviously with the overall timeout being capped to some upper bound (like 3 seconds). I think we should consider that design since it could be more of a global pattern we want to implement for trigger functions more generally.

:thinking: when doing a request many, there is no timeout for single messages. There's just the time we wait, period.

**Comment by kthomas** [comment]
Attempting to use the following implementation (async subscription and `time.Ticker`) for `handleRequestMany` resulted in the subscription receiving empty messages when requested by the agent:

```
func (m *MessagingService) handleRequestMany(msg *nats.Msg) {
	subject := msg.Header.Get(messageSubject)
	if subject == "" {
		resp, _ := json.Marshal(&agentapi.HostServicesMessagingResponse{
			Errors: []string{"subject is required"},
		})

		err := msg.Respond(resp)
		if err != nil {
			m.log.Error(fmt.Sprintf("failed to respond to host services RPC request: %s", err.Error()))
		}
		return
	}

	// create a new response inbox and subscribe
	replyTo := m.nc.NewRespInbox()
	sub, err := m.nc.Subscribe(replyTo, func(resp *nats.Msg) {
		m.log.Debug(fmt.Sprintf("received %d-byte response to request on subject: %s", len(resp.Data), subject))

		// respond to the requestMany message
		err := msg.Respond(resp.Data)
		if err != nil {
			m.log.Error(fmt.Sprintf("failed to publish %d-byte response to reply subject: %s: %s", len(resp.Data), msg.Reply, err.Error()))
		}
	})
	if err != nil {
		resp, _ := json.Marshal(&agentapi.HostServicesMessagingResponse{
			Errors: []string{fmt.Sprintf("failed to subscribe to response inbox: %s", err.Error())},
		})

		err := msg.Respond(resp)
		if err != nil {
			m.log.Error(fmt.Sprintf("failed to respond to host services RPC request: %s", err.Error()))
		}
		return
	}

	defer func() {
		_ = sub.Unsubscribe()
	}()

	_ = m.nc.Flush()

	ticker := time.NewTicker(messagingRequestManyTimeout)
	defer ticker.Stop()

	// publish the original requestMany request to the target subject
	err = m.nc.PublishRequest(subject, replyTo, msg.Data)
	if err != nil {
		resp, _ := json.Marshal(&agentapi.HostServicesMessagingResponse{
			Errors: []string{fmt.Sprintf("failed to send %d-byte request to subject: %s: %s", len(msg.Data), subject, err.Error())},
		})

		err := msg.Respond(resp)
		if err != nil {
			m.log.Error(fmt.Sprintf("failed to respond to host services RPC request: %s", err.Error()))
		}

		return
	}

	<-ticker.C
}
```

**Review by autodidaddict — APPROVED** [review]
LGTM. We can look into ways to optimize the collect-and-respond proxy in the middle in some future PR

**Pull request merged**
