### PR TITLE
Add DNS support for external name resolution

### PR DESCRIPTION
**Pull request by kthomas**
This PR equips the nex node with an embedded nameserver, running on an ephemeral port, which is provided to sandboxed agent VMs via Firecracker MMDS. The agent uses iptables to setup NAT OUTPUT chain rules for sending local DNS packets destined for port 53 (UDP or TCP) to the configured nameserver.

### CODE REVIEW

**Comment by autodidaddict** [comment]
So we weren't able to do this with just configuration? :sob:

**Comment by autodidaddict** [comment]
Is it possible to check the node configuration and only activate the DNS stuff is sandbox is on? If the node isn't using firecracker then running the embedded DNS is unnecessary

**Comment by kthomas** [comment]
> Is it possible to check the node configuration and only activate the DNS stuff is sandbox is on? If the node isn't using firecracker then running the embedded DNS is unnecessary

Yes, and definitely something I wanted to bring up. Will only activate this in sandbox mode.

**Review by jordan-rash — APPROVED** [review]
Dope!

**Pull request merged**
