### PR TITLE
Set VM metadata outside of VM creation

### PR DESCRIPTION
**Pull request by kthomas**
This commit handles some small cleanup items to make things more consistent.

### CODE REVIEW

**Comment by autodidaddict** [comment]
Can you elaborate on what problems or situations this resolves? You mention that it makes things more consistent but I'm not sure how or how things were inconsistent prior to this.

**Comment by autodidaddict** [comment]
Also need to make sure this passes the build/lint

**Comment by kthomas** [comment]
Previously we were setting metadata within firecracker VM creation but it is more readable and extensible if that takes place in machine manager.

The inconsistencies were just related to syntax itself.

**Comment by autodidaddict** [comment]
Ok I thought maybe there was a race condition involving _when_ we set the metadata, not just a change of roles as to which struct sets it. As long as the metadata is still being set at the right time, this looks fine.

**Comment by kthomas** [comment]
> Also need to make sure this passes the build/lint

It passes.

**Review by autodidaddict — APPROVED** [review]

**Pull request merged**
